# Generated by Django 4.2.7 on 2025-03-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadAutonoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diocesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('url', models.URLField()),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('grabado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_grabados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comunidad_autonoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.comunidadautonoma')),
            ],
        ),
        migrations.CreateModel(
            name='building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(max_length=50)),
                ('referencia_catastral', models.CharField(max_length=20)),
                ('numero_finca', models.CharField(max_length=20)),
                ('descripcion_registral', models.TextField()),
                ('vendido', models.BooleanField(default=False)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ciudad_venta', models.CharField(blank=True, max_length=100, null=True)),
                ('notario', models.CharField(blank=True, max_length=100, null=True)),
                ('incluye_bienes_muebles', models.BooleanField(default=False)),
                ('grado_proteccion', models.CharField(blank=True, max_length=100, verbose_name='Grado de Protección')),
                ('tipo_adquiriente', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Adquiriente')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('comunidad_autonoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.comunidadautonoma')),
                ('diocesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.diocesis')),
                ('documents', models.ManyToManyField(to='heritage_buildings.document')),
                ('grabado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings_grabados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings_modificados', to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.provincia')),
                ('registro_propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.registropropiedad')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heritage_buildings.tipodocument'),
        ),
    ]
