# Generated by Django 4.2.7 on 2025-03-10 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
