# Generated by Django 4.2.7 on 2025-03-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0003_auto_20250310_1505'),
    ]

    operations = [
    ]
