# Generated by Django 4.2.7 on 2025-03-10 15:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heritage_buildings', '0004_auto_20250310_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Documento')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'odt', 'rtf'])], verbose_name='Archivo (PDF o Texto)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL del Documento (opcional)')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Grabación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='GradoProteccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Grado de Protección',
                'verbose_name_plural': 'Grados de Protección',
            },
        ),
        migrations.CreateModel(
            name='TipoAdquiriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Adquiriente',
                'verbose_name_plural': 'Tipos de Adquirientes',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100, unique=True, verbose_name='Denominación')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='grabado_por',
        ),
        migrations.RemoveField(
            model_name='document',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tipo',
        ),
        migrations.AlterModelOptions(
            name='comunidadautonoma',
            options={'verbose_name': 'Comunidad Autónoma', 'verbose_name_plural': 'Comunidades Autónomas'},
        ),
        migrations.AlterModelOptions(
            name='diocesis',
            options={'verbose_name': 'Diócesis', 'verbose_name_plural': 'Diócesis'},
        ),
        migrations.AlterModelOptions(
            name='edificio',
            options={'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='registropropiedad',
            options={'verbose_name': 'Registro de Propiedad', 'verbose_name_plural': 'Registros de Propiedad'},
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='documents',
        ),
        migrations.AlterField(
            model_name='comunidadautonoma',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='diocesis',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='ciudad_venta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad de Venta'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='comunidad_autonoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.comunidadautonoma', verbose_name='Comunidad Autónoma'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='coordenadas',
            field=models.CharField(max_length=50, verbose_name='Coordenadas (lat, lon)'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='descripcion_registral',
            field=models.TextField(verbose_name='Descripción Registral'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='diocesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.diocesis', verbose_name='Diócesis'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='fecha_grabacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Grabación'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='grabado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_grabados', to=settings.AUTH_USER_MODEL, verbose_name='Grabado por'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='incluye_bienes_muebles',
            field=models.BooleanField(default=False, verbose_name='Incluye Bienes Muebles'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='municipio',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del Edificio'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='notario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Notario'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='numero_finca',
            field=models.CharField(max_length=20, verbose_name='Número de Finca'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio (€)'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='referencia_catastral',
            field=models.CharField(max_length=20, unique=True, verbose_name='Referencia Catastral'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='registro_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.registropropiedad', verbose_name='Registro de Propiedad'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='comunidad_autonoma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='heritage_buildings.comunidadautonoma', verbose_name='Comunidad Autónoma'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='registropropiedad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['nombre', 'municipio'], name='heritage_bu_nombre_1b709a_idx'),
        ),
        migrations.AddIndex(
            model_name='edificio',
            index=models.Index(fields=['referencia_catastral'], name='heritage_bu_referen_3e08ed_idx'),
        ),
        migrations.DeleteModel(
            name='document',
        ),
        migrations.DeleteModel(
            name='TipoDocument',
        ),
        migrations.AddField(
            model_name='documento',
            name='grabado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_grabados', to=settings.AUTH_USER_MODEL, verbose_name='Grabado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='heritage_buildings.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='edificios', to='heritage_buildings.documento', verbose_name='Documentos Asociados'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='grado_proteccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios', to='heritage_buildings.gradoproteccion', verbose_name='Grado de Protección'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='tipo_adquiriente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios', to='heritage_buildings.tipoadquiriente', verbose_name='Tipo de Adquiriente'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['fecha', 'tipo'], name='heritage_bu_fecha_ae70a5_idx'),
        ),
    ]
