# Generated by Django 4.2.7 on 2025-03-10 18:37

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heritage_buildings', '0005_documento_gradoproteccion_tipoadquiriente_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='edificio',
            name='heritage_bu_nombre_1b709a_idx',
        ),
        migrations.RemoveIndex(
            model_name='edificio',
            name='heritage_bu_referen_3e08ed_idx',
        ),
        migrations.AddField(
            model_name='registropropiedad',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='registropropiedad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='registropropiedad',
            name='titular',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='diocesis',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'odt', 'rtf', 'jpg', 'mp4'])], verbose_name='Archivo (PDF,Texto,Foto o Video)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='grabado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_grabados', to=settings.AUTH_USER_MODEL, verbose_name='Grabado por'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Coordenadas (lat, lon)'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='descripcion_registral',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Registral'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='diocesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.diocesis', verbose_name='Diócesis'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='grabado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_grabados', to=settings.AUTH_USER_MODEL, verbose_name='Grabado por'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='modificado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edificios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='numero_finca',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Finca'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='referencia_catastral',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Referencia Catastral'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='registro_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='heritage_buildings.registropropiedad', verbose_name='Registro de Propiedad'),
        ),
    ]
