# Generated by Django 4.2.7 on 2025-03-10 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0006_remove_edificio_heritage_bu_nombre_1b709a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_relacionados', to='heritage_buildings.edificio', verbose_name='Edificio'),
            preserve_default=False,
        ),
    ]
