# Generated by Django 4.2.7 on 2025-03-12 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0007_documento_edificio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor(es)')),
                ('tipo_identificador', models.CharField(choices=[('ISBN', 'ISBN'), ('DOI', 'DOI'), ('ISSN', 'ISSN')], max_length=10, verbose_name='Tipo de Identificador')),
                ('identificador', models.CharField(max_length=100, unique=True, verbose_name='Identificador')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Bibliografía',
                'verbose_name_plural': 'Bibliografías',
            },
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_grabacion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='grabado_por',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='ciudad_venta',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='descripcion_registral',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='fecha_grabacion',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='grabado_por',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='incluye_bienes_muebles',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='modificado_por',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='notario',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='numero_finca',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='vendido',
        ),
        migrations.AlterField(
            model_name='comunidadautonoma',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Comunidad Autónoma'),
        ),
        migrations.AlterField(
            model_name='diocesis',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Diócesis'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'doc', 'docx', 'odt', 'rtf', 'jpg', 'mp4'])], verbose_name='Archivo (PDF, Texto, Foto o Video)'),
        ),
        migrations.AlterField(
            model_name='gradoproteccion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Grado de Protección'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='tipoadquiriente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tipo de Adquiriente'),
        ),
        migrations.CreateModel(
            name='ReferenciaBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volumen')),
                ('paginas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Intervalo de Páginas')),
                ('bibliografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='heritage_buildings.bibliografia', verbose_name='Bibliografía')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_bibliograficas', to='heritage_buildings.edificio', verbose_name='Edificio')),
            ],
            options={
                'verbose_name': 'Referencia Bibliográfica',
                'verbose_name_plural': 'Referencias Bibliográficas',
            },
        ),
    ]
