# Generated by Django 4.2.7 on 2025-03-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0008_bibliografia_remove_documento_fecha_grabacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='desacralizado',
            field=models.BooleanField(default=False, verbose_name='Desacralizado'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='incluye_bienes_muebles',
            field=models.BooleanField(default=False, verbose_name='Incluye Bienes Móviles'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
