# Generated by Django 4.2.7 on 2025-03-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0009_edificio_desacralizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='ciudad_venta',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad de Venta'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='descripcion_registral',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Registral'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='fecha_venta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='notario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notario'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='numero_finca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Finca'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Venta'),
        ),
    ]
