# Generated by Django 4.2.7 on 2025-03-12 13:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0010_edificio_ciudad_venta_edificio_descripcion_registral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='coordenadas',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordenadas Geográficas'),
        ),
    ]
