# Generated by Django 4.2.7 on 2025-03-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritage_buildings', '0011_edificio_coordenadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='incluye_bienes_muebles',
            field=models.BooleanField(default=False, verbose_name='Incluye Bienes Muebles'),
        ),
    ]
