name: CI & Deploy (Render)
on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

concurrency:
  group: render-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (if any)
        run: |
          if [ -f 'pytest.ini' ] || [ -d 'tests' ]; then
            pip install pytest
            pytest -q
          else
            echo 'No tests found. Skipping.'
          fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Trigger Render deploy via Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo '❌ Missing secret RENDER_DEPLOY_HOOK_URL'; exit 1
          fi
          curl -fsS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo '✅ Deploy triggered'
